USE accounts;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

START TRANSACTION;

UPDATE users SET age=12 WHERE email='jen.cole@example.com';
SELECT * FROM users;

ROLLBACK;

START TRANSACTION;
SELECT * FROM users;
COMMIT;
